# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  allow_different_nesting: false
  # Only check sibling headings
  siblings_only: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 160
  # Number of characters for headings
  heading_line_length: 160
  # Number of characters for code blocks
  code_block_line_length: 160
